# Generated by Django 5.0 on 2023-12-14 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("comment", models.CharField(max_length=200)),
                ("image_url", models.URLField(max_length=2048)),
                (
                    "yum_factor",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cake",
            constraint=models.CheckConstraint(
                check=models.Q(("yum_factor__gte", 1), ("yum_factor__lte", 5)),
                name="A yum_factor value is valid between 1 and 5",
            ),
        ),
    ]
