version: '3.8'

services:
  waracle_cake_postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data:delegated
    restart: always
    env_file:
      - ../environment/.env

  waracle_cake_app:
    build:
      context: ../
      dockerfile: ./develop/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../application:/code
    ports:
      - "80:8000"
    env_file:
      - ../environment/.env
    depends_on:
      - waracle_cake_postgres
